name=MH-T7042A Library
version=1.0.0
author=acapovilla
maintainer=acapovilla
sentence=Arduino library for MH-T7042A sensors.
paragraph=Arduino library for MH-T7042A infrared CH4 gas sensors.
category=Sensors
url=https://github.com/acapovilla/MH-T7042A_Library
architectures=*
depends=
